### ISSUE TITLE
英文it's中的中英文转换及空格问题

### ISSUE THREAD

**Issue by RediYo** [next-theme/hexo-pangu#10]
遇到的問題
it's 会变成 it‘s，即英文的 ' 会变成中文的 ’ 导致错误的空格 it's 变成 it‘ s

**Comment by stevenjoezhang** [comment]
这个问题与 Markdown 渲染插件的设置有关，参考
https://github.com/next-theme/hexo-theme-next/discussions/681
https://github.com/theme-next/hexo-theme-next/issues/462#issuecomment-435429592
