### ISSUE TITLE
js 文件 `>` 被转义

### ISSUE THREAD

**Issue by MHuiG** [next-theme/hexo-pangu#4]
步骤
1. 在 `blog-source/source/` 文件夹下创建文件 0.js 
 ```js
const a=()=>{
  
}
```
2. hexo s
3.  see bug
![image](https://user-images.githubusercontent.com/38281581/151480218-ee27ff5a-d4d8-4d74-a987-f2dcbc5da05b.png)

版本信息
![image](https://user-images.githubusercontent.com/38281581/151479963-8c57a0f4-fd7c-4eb5-8a49-342413a53728.png)

移除 hexo-pangu 后正常:
![image](https://user-images.githubusercontent.com/38281581/151480378-61b489b6-0e90-4e0c-8f06-7ec101c760bb.png)

另外 `theme/source/` 文件夹下创建文件 0.js 是正常的

**Comment by stevenjoezhang** [comment]
Hexo 已知问题： https://github.com/hexojs/hexo/issues/4468
需要设置 `skip_render`:
```yml
skip_render:
  - 0.js
```
